"""Deterministic DATA-1.5 market-data quality domain."""

from app.market_data.quality.contracts import (
    AssessmentIdentity,
    AssessmentRunIdentity,
    DependencyOutcome,
    EvaluationContext,
    QualityDisposition,
    QualityPolicyIdentity,
    QualityPolicyVersionIdentity,
    QualitySeverity,
    ReceiptBasis,
    TargetKind,
)
from app.market_data.quality.dependency_resolution import (
    RankedCandidate,
    RankedResolution,
    TemporalCandidate,
    TemporalResolution,
    resolve_ranked_candidates,
    resolve_temporal_candidates,
)
from app.market_data.quality.evaluator import (
    ConnectionFact,
    MarketStatusFact,
    ProvenanceDependencyFact,
    QualityEvaluationInput,
    QualityEvaluationResult,
    QuoteTarget,
    SessionFact,
    StatusTarget,
    SubscriptionFact,
    SubscriptionResolutionState,
    TargetDependencies,
    evaluate_quality,
)
from app.market_data.quality.policy_parser import parse_quality_policy
from app.market_data.quality.policy_schema import ParsedQualityPolicy

__all__ = [
    "AssessmentIdentity",
    "AssessmentRunIdentity",
    "ConnectionFact",
    "DependencyOutcome",
    "EvaluationContext",
    "MarketStatusFact",
    "ParsedQualityPolicy",
    "ProvenanceDependencyFact",
    "QualityDisposition",
    "QualityEvaluationInput",
    "QualityEvaluationResult",
    "QualityPolicyIdentity",
    "QualityPolicyVersionIdentity",
    "QualitySeverity",
    "QuoteTarget",
    "RankedCandidate",
    "RankedResolution",
    "ReceiptBasis",
    "SessionFact",
    "StatusTarget",
    "SubscriptionFact",
    "SubscriptionResolutionState",
    "TargetDependencies",
    "TargetKind",
    "TemporalCandidate",
    "TemporalResolution",
    "evaluate_quality",
    "parse_quality_policy",
    "resolve_ranked_candidates",
    "resolve_temporal_candidates",
]
